#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "arkalib"
name = "ARKALIB"
description.en = "Create and track budgets without requiring advanced accounting knowledge."
description.fr = "Créer et de suivre des budgets en toute simplicité sans notion comptable avancée."

version = "0.1~ynh1"

maintainers = []

[upstream]
license = "MIT"

code = "https://github.com/BaptisteCHRPN/arkalib"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/arkalib"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/BaptisteCHRPN/arkalib/archive/eddd38adfc857526dd26c575cb20377f67d9f47b.tar.gz"
        sha256 = "fa51dddfdbf0585477ea8224bed9a974f0efb98bdcd9064f0f0c0fac2772762f"

        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php8.3-fpm",
        "php8.3-cli",
        "php8.3-pdo",
        "php8.3-mysql",
        "php8.3-intl",
        "php8.3-mbstring",
        "php8.3-xml",
        "php8.3-fileinfo",
        "mariadb-server",
    ]

    [resources.database]
    type = "mysql"

    [resources.composer]
    version = "2.8.3"
