#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "arkalib"
name = "ARKALIB"
description.en = "Create and track budgets without requiring advanced accounting knowledge."
description.fr = "Créer et de suivre des budgets en toute simplicité sans notion comptable avancée."

version = "0.1~ynh1"

maintainers = []

[upstream]
license = "MIT"

code = "https://github.com/BaptisteCHRPN/arkalib"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/arkalib"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/BaptisteCHRPN/arkalib/archive/18d30fce30a2b333c71ef4d12ca569a963b54b19.tar.gz"
        sha256 = "56f10520f678b8a93e9f92c211fbf58344cced36feb258d86ef34030206d45ab"

        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php8.3-fpm",
        "php8.3-cli",
        "php8.3-pdo",
        "php8.3-mysql",
        "php8.3-intl",
        "php8.3-mbstring",
        "php8.3-xml",
        "php8.3-fileinfo",
        "mariadb-server",
    ]

    [resources.database]
    type = "mysql"

    [resources.composer]
    version = "2.8.3"
