#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

secret=$(ynh_string_random --length=32)
ynh_app_setting_set --key=secret --value=$secret

admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

ynh_app_setting_set --key=php_upload_max_filesize --value=50M
ynh_app_setting_set --key=php_post_max_size --value=50M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env.local" --destination="$install_dir/.env.local"

chmod 400 "$install_dir/.env.local"
chown "$app:$app" "$install_dir/.env.local"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing $app..."

pushd $install_dir
  ynh_composer_exec install --no-dev --optimize-autoloader
  ynh_exec_as_app "php$php_version" bin/console importmap:install
  ynh_exec_as_app "php$php_version" bin/console asset-map:compile
  ynh_exec_as_app "php$php_version" bin/console doctrine:migrations:migrate --no-interaction
  ynh_exec_as_app "php$php_version" bin/console cache:clear
  ynh_exec_as_app "php$php_version" bin/console cache:warmup
  ynh_exec_as_app "php$php_version" bin/console app:create-user "$admin_mail" "$password" true ROLE_ADMIN
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
