#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env.local"

chown -R "$app:www-data" "$install_dir"

#=================================================
# UPDATE APP
#=================================================
ynh_script_progression "Updating $app..."

pushd $install_dir
  ynh_composer_exec install --no-dev --optimize-autoloader
  ynh_exec_as_app "php$php_version" bin/console importmap:install
  ynh_exec_as_app "php$php_version" bin/console asset-map:compile
  ynh_exec_as_app "php$php_version" bin/console doctrine:migrations:migrate --no-interaction
  ynh_exec_as_app "php$php_version" bin/console cache:clear
  ynh_exec_as_app "php$php_version" bin/console cache:warmup
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
